export const countries = [
    { code: "PW", name: "Palau", flag: "🇵🇼" },
    { code: "GL", name: "Greenland", flag: "🇬🇱" },
    { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
    { code: "GM", name: "Gambia", flag: "🇬🇲" },
    { code: "PY", name: "Paraguay", flag: "🇵🇾" },
    { code: "TG", name: "Togo", flag: "🇹🇬" },
    { code: "BH", name: "Bahrain", flag: "🇧🇭" },
    { code: "GN", name: "Guinea", flag: "🇬🇳" },
    { code: "ER", name: "Eritrea", flag: "🇪🇷" },
    { code: "NG", name: "Nigeria", flag: "🇳🇬" },
    { code: "KW", name: "Kuwait", flag: "🇰🇼" },
    { code: "CN", name: "China", flag: "🇨🇳" },
    { code: "NL", name: "Netherlands", flag: "🇳🇱" },
    { code: "ID", name: "Indonesia", flag: "🇮🇩" },
    { code: "BS", name: "Bahamas", flag: "🇧🇸" },
    { code: "TN", name: "Tunisia", flag: "🇹🇳" },
    { code: "GA", name: "Gabon", flag: "🇬🇦" },
    { code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
    { code: "TR", name: "Turkey", flag: "🇹🇷" },
    { code: "ZA", name: "South Africa", flag: "🇿🇦" },
    { code: "ME", name: "Montenegro", flag: "🇲🇪" },
    { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
    { code: "CZ", name: "Czechia", flag: "🇨🇿" },
    { code: "SR", name: "Suriname", flag: "🇸🇷" },
    { code: "PF", name: "French Polynesia", flag: "🇵🇫" },
    { code: "PH", name: "Philippines", flag: "🇵🇭" },
    { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
    { code: "HN", name: "Honduras", flag: "🇭🇳" },
    { code: "MX", name: "Mexico", flag: "🇲🇽" },
    { code: "TO", name: "Tonga", flag: "🇹🇴" },
    { code: "LC", name: "Saint Lucia", flag: "🇱🇨" },
    { code: "FM", name: "Micronesia", flag: "🇫🇲" },
    { code: "RO", name: "Romania", flag: "🇷🇴" },
    { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
    { code: "TC", name: "Turks and Caicos Islands", flag: "🇹🇨" },
    { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
    { code: "FJ", name: "Fiji", flag: "🇫🇯" },
    { code: "LS", name: "Lesotho", flag: "🇱🇸" },
    { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
    { code: "LT", name: "Lithuania", flag: "🇱🇹" },
    { code: "BN", name: "Brunei", flag: "🇧🇳" },
    { code: "EE", name: "Estonia", flag: "🇪🇪" },
    { code: "HU", name: "Hungary", flag: "🇭🇺" },
    { code: "NO", name: "Norway", flag: "🇳🇴" },
    { code: "NC", name: "New Caledonia", flag: "🇳🇨" },
    { code: "SG", name: "Singapore", flag: "🇸🇬" },
    { code: "FR", name: "France", flag: "🇫🇷" },
    { code: "SI", name: "Slovenia", flag: "🇸🇮" },
    { code: "GE", name: "Georgia", flag: "🇬🇪" },
    { code: "FI", name: "Finland", flag: "🇫🇮" },
    { code: "LA", name: "Laos", flag: "🇱🇦" },
    { code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
    { code: "IL", name: "Israel", flag: "🇮🇱" },
    { code: "MO", name: "Macao", flag: "🇲🇴" },
    { code: "NR", name: "Nauru", flag: "🇳🇷" },
    { code: "AU", name: "Australia", flag: "🇦🇺" },
    { code: "GD", name: "Grenada", flag: "🇬🇩" },
    { code: "NP", name: "Nepal", flag: "🇳🇵" },
    { code: "CY", name: "Cyprus", flag: "🇨🇾" },
    { code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
    { code: "RS", name: "Serbia", flag: "🇷🇸" },
    { code: "OM", name: "Oman", flag: "🇴🇲" },
    { code: "EG", name: "Egypt", flag: "🇪🇬" },
    { code: "SB", name: "Solomon Islands", flag: "🇸🇧" },
    { code: "BI", name: "Burundi", flag: "🇧🇮" },
    { code: "MU", name: "Mauritius", flag: "🇲🇺" },
    { code: "BJ", name: "Benin", flag: "🇧🇯" },
    { code: "QA", name: "Qatar", flag: "🇶🇦" },
    { code: "RW", name: "Rwanda", flag: "🇷🇼" },
    { code: "KH", name: "Cambodia", flag: "🇰🇭" },
    { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
    { code: "AR", name: "Argentina", flag: "🇦🇷" },
    { code: "DK", name: "Denmark", flag: "🇩🇰" },
    { code: "UY", name: "Uruguay", flag: "🇺🇾" },
    { code: "CW", name: "Curaçao", flag: "🇨🇼" },
    { code: "MN", name: "Mongolia", flag: "🇲🇳" },
    { code: "AM", name: "Armenia", flag: "🇦🇲" },
    { code: "IN", name: "India", flag: "🇮🇳" },
    { code: "MH", name: "Marshall Islands", flag: "🇲🇭" },
    { code: "NE", name: "Niger", flag: "🇳🇪" },
    { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
    { code: "MV", name: "Maldives", flag: "🇲🇻" },
    { code: "PG", name: "Papua New Guinea", flag: "🇵🇬" },
    { code: "JP", name: "Japan", flag: "🇯🇵" },
    { code: "WS", name: "Samoa", flag: "🇼🇸" },
    { code: "GH", name: "Ghana", flag: "🇬🇭" },
    { code: "MG", name: "Madagascar", flag: "🇲🇬" },
    { code: "BT", name: "Bhutan", flag: "🇧🇹" },
    { code: "MK", name: "North Macedonia", flag: "🇲🇰" },
    { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹" },
    { code: "BO", name: "Bolivia", flag: "🇧🇴" },
    { code: "DE", name: "Germany", flag: "🇩🇪" },
    { code: "AT", name: "Austria", flag: "🇦🇹" },
    { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
    { code: "SC", name: "Seychelles", flag: "🇸🇨" },
    { code: "IQ", name: "Iraq", flag: "🇮🇶" },
    { code: "MT", name: "Malta", flag: "🇲🇹" },
    { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
    { code: "PE", name: "Peru", flag: "🇵🇪" },
    { code: "SX", name: "Sint Maarten", flag: "🇸🇽" },
    { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
    { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
    { code: "AL", name: "Albania", flag: "🇦🇱" },
    { code: "CL", name: "Chile", flag: "🇨🇱" },
    { code: "ES", name: "Spain", flag: "🇪🇸" },
    { code: "MW", name: "Malawi", flag: "🇲🇼" },
    { code: "BM", name: "Bermuda", flag: "🇧🇲" },
    { code: "EC", name: "Ecuador", flag: "🇪🇨" },
    { code: "IS", name: "Iceland", flag: "🇮🇸" },
    { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
    { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
    { code: "MR", name: "Mauritania", flag: "🇲🇷" },
    { code: "GT", name: "Guatemala", flag: "🇬🇹" },
    { code: "BW", name: "Botswana", flag: "🇧🇼" },
    { code: "GR", name: "Greece", flag: "🇬🇷" },
    { code: "MY", name: "Malaysia", flag: "🇲🇾" },
    { code: "ZM", name: "Zambia", flag: "🇿🇲" },
    { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
    { code: "TH", name: "Thailand", flag: "🇹🇭" },
    { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
    { code: "SV", name: "El Salvador", flag: "🇸🇻" },
    { code: "SK", name: "Slovakia", flag: "🇸🇰" },
    { code: "SE", name: "Sweden", flag: "🇸🇪" },
    { code: "CA", name: "Canada", flag: "🇨🇦" },
    { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
    { code: "KM", name: "Comoros", flag: "🇰🇲" },
    { code: "US", name: "United States", flag: "🇺🇸" },
    { code: "BE", name: "Belgium", flag: "🇧🇪" },
    { code: "SM", name: "San Marino", flag: "🇸🇲" },
    { code: "KI", name: "Kiribati", flag: "🇰🇮" },
    { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
    { code: "LR", name: "Liberia", flag: "🇱🇷" },
    { code: "AW", name: "Aruba", flag: "🇦🇼" },
    { code: "TW", name: "Taiwan", flag: "🇹🇼" },
    { code: "IE", name: "Ireland", flag: "🇮🇪" },
    { code: "BZ", name: "Belize", flag: "🇧🇿" },
    { code: "CH", name: "Switzerland", flag: "🇨🇭" },
    { code: "PT", name: "Portugal", flag: "🇵🇹" },
    { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "TV", name: "Tuvalu", flag: "🇹🇻" },
    { code: "CO", name: "Colombia", flag: "🇨🇴" },
    { code: "MA", name: "Morocco", flag: "🇲🇦" },
    { code: "DM", name: "Dominica", flag: "🇩🇲" },
    { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
    { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬" },
    { code: "LV", name: "Latvia", flag: "🇱🇻" },
    { code: "GY", name: "Guyana", flag: "🇬🇾" },
    { code: "PL", name: "Poland", flag: "🇵🇱" },
    { code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
    { code: "TD", name: "Chad", flag: "🇹🇩" },
    { code: "IT", name: "Italy", flag: "🇮🇹" },
    { code: "AD", name: "Andorra", flag: "🇦🇩" },
    { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
    { code: "KR", name: "South Korea", flag: "🇰🇷" },
    { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
    { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
    { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
    { code: "BR", name: "Brazil", flag: "🇧🇷" }
  ];